### PR TITLE
some change

### PR DESCRIPTION
**Pull request by quert999**
use soundpool to play sounds

### CODE REVIEW

**Comment by sudip-mondal-2002** [comment]
image
Thank you for creating this pull.
The grid layout is distorted a bit(maybe not for all devices), please check it
You may run the emulator for a small screen size mobile. It will be easy to debug.
Thanking you...

**Review by sudip-mondal-2002 — CHANGES_REQUESTED** [review]
Grid layout problem still NOT fixed, try to fix it.
Sudggestion: try to resize(make smaller) the imageViews

**Comment by quert999** [comment]
The display on my mobile phone(honor v20) is normal. There is no corresponding mobile phone to test and solve this problem. It should be the display problem of GridView on some models

**Comment by sudip-mondal-2002** [comment]
Yes, it will not problematic in all phones, you can test it through different emulators.

**Comment by sudip-mondal-2002** [comment]
Woah!! Great work bro .. Hope I will get your contribution in future projects also.
You are lit !!!

**Pull request merged**
